# Generated by Django 4.2.9 on 2025-02-28 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='duration',
            field=models.IntegerField(default=60, help_text='Duration in minutes'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
