# Generated by Django 4.2.9 on 2025-02-28 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={},
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='level',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='points',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='title',
        ),
        migrations.AddField(
            model_name='achievement',
            name='name',
            field=models.CharField(default='Achievement', max_length=255),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
